
package com.pb.engageone.ws.delivery;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DeliveryService", targetNamespace = "http://pb.com/EngageOne/ws/delivery", wsdlLocation = "http://localhost.ntuc.local:18080/EngageOneWS/DeliveryService?wsdl")
public class DeliveryService_Service
    extends Service
{

    private final static URL DELIVERYSERVICE_WSDL_LOCATION;
    private final static WebServiceException DELIVERYSERVICE_EXCEPTION;
    private final static QName DELIVERYSERVICE_QNAME = new QName("http://pb.com/EngageOne/ws/delivery", "DeliveryService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost.ntuc.local:18080/EngageOneWS/DeliveryService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DELIVERYSERVICE_WSDL_LOCATION = url;
        DELIVERYSERVICE_EXCEPTION = e;
    }

    public DeliveryService_Service() {
        super(__getWsdlLocation(), DELIVERYSERVICE_QNAME);
    }

    public DeliveryService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DELIVERYSERVICE_QNAME, features);
    }

    public DeliveryService_Service(URL wsdlLocation) {
        super(wsdlLocation, DELIVERYSERVICE_QNAME);
    }

    public DeliveryService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DELIVERYSERVICE_QNAME, features);
    }

    public DeliveryService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeliveryService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DeliveryService
     */
    @WebEndpoint(name = "DeliveryServiceSOAP")
    public DeliveryService getDeliveryServiceSOAP() {
        return super.getPort(new QName("http://pb.com/EngageOne/ws/delivery", "DeliveryServiceSOAP"), DeliveryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeliveryService
     */
    @WebEndpoint(name = "DeliveryServiceSOAP")
    public DeliveryService getDeliveryServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://pb.com/EngageOne/ws/delivery", "DeliveryServiceSOAP"), DeliveryService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DELIVERYSERVICE_EXCEPTION!= null) {
            throw DELIVERYSERVICE_EXCEPTION;
        }
        return DELIVERYSERVICE_WSDL_LOCATION;
    }

}
