
package com.pb.engageone.ws.delivery;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DeliveryService", targetNamespace = "http://pb.com/EngageOne/ws/delivery")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.pb.engageone.ws.delivery.ObjectFactory.class,
    com.pb.engageone.ws.common.ObjectFactory.class,
    com.pb.engageone.ws.model.ObjectFactory.class
})
public interface DeliveryService {


    /**
     * 
     * @param request
     * @return
     *     returns com.pb.engageone.ws.delivery.SearchDeliveryItemsResponse
     * @throws DeliveryFault
     */
    @WebMethod(action = "http://pb.com/EngageOne/ws/delivery/SearchDeliveryItems")
    @WebResult(name = "SearchDeliveryItemsResponse", targetNamespace = "http://pb.com/EngageOne/ws/delivery", partName = "response")
    public SearchDeliveryItemsResponse searchDeliveryItems(
        @WebParam(name = "SearchDeliveryItems", targetNamespace = "http://pb.com/EngageOne/ws/delivery", partName = "request")
        SearchDeliveryItems request)
        throws DeliveryFault
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.pb.engageone.ws.delivery.SuspendDeliveryItemResponse
     * @throws DeliveryFault
     */
    @WebMethod(action = "http://pb.com/EngageOne/ws/delivery/SuspendDeliveryItem")
    @WebResult(name = "SuspendDeliveryItemResponse", targetNamespace = "http://pb.com/EngageOne/ws/delivery", partName = "response")
    public SuspendDeliveryItemResponse suspendDeliveryItem(
        @WebParam(name = "SuspendDeliveryItem", targetNamespace = "http://pb.com/EngageOne/ws/delivery", partName = "request")
        SuspendDeliveryItem request)
        throws DeliveryFault
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.pb.engageone.ws.delivery.ResumeDeliveryItemResponse
     * @throws DeliveryFault
     */
    @WebMethod(action = "http://pb.com/EngageOne/ws/delivery/ResumeDeliveryItem")
    @WebResult(name = "ResumeDeliveryItemResponse", targetNamespace = "http://pb.com/EngageOne/ws/delivery", partName = "response")
    public ResumeDeliveryItemResponse resumeDeliveryItem(
        @WebParam(name = "ResumeDeliveryItem", targetNamespace = "http://pb.com/EngageOne/ws/delivery", partName = "request")
        ResumeDeliveryItem request)
        throws DeliveryFault
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.pb.engageone.ws.delivery.DeleteDeliveryItemResponse
     * @throws DeliveryFault
     */
    @WebMethod(action = "http://pb.com/EngageOne/ws/delivery/DeleteDeliveryItem")
    @WebResult(name = "DeleteDeliveryItemResponse", targetNamespace = "http://pb.com/EngageOne/ws/delivery", partName = "response")
    public DeleteDeliveryItemResponse deleteDeliveryItem(
        @WebParam(name = "DeleteDeliveryItem", targetNamespace = "http://pb.com/EngageOne/ws/delivery", partName = "request")
        DeleteDeliveryItem request)
        throws DeliveryFault
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.pb.engageone.ws.delivery.UpdateDeliveryItemResponse
     * @throws DeliveryFault
     */
    @WebMethod(action = "http://pb.com/EngageOne/ws/delivery/UpdateDeliveryItem")
    @WebResult(name = "UpdateDeliveryItemResponse", targetNamespace = "http://pb.com/EngageOne/ws/delivery", partName = "response")
    public UpdateDeliveryItemResponse updateDeliveryItem(
        @WebParam(name = "UpdateDeliveryItem", targetNamespace = "http://pb.com/EngageOne/ws/delivery", partName = "request")
        UpdateDeliveryItem request)
        throws DeliveryFault
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.pb.engageone.ws.delivery.PreviewWorkItemResponse
     * @throws DeliveryFault
     */
    @WebMethod(action = "http://pb.com/EngageOne/ws/delivery/PreviewWorkItem")
    @WebResult(name = "PreviewWorkItemResponse", targetNamespace = "http://pb.com/EngageOne/ws/delivery", partName = "response")
    public PreviewWorkItemResponse previewWorkItem(
        @WebParam(name = "PreviewWorkItem", targetNamespace = "http://pb.com/EngageOne/ws/delivery", partName = "request")
        PreviewWorkItem request)
        throws DeliveryFault
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.pb.engageone.ws.delivery.PreviewDocumentResponse
     * @throws DeliveryFault
     */
    @WebMethod(action = "http://pb.com/EngageOne/ws/delivery/PreviewDocument")
    @WebResult(name = "PreviewDocumentResponse", targetNamespace = "http://pb.com/EngageOne/ws/delivery", partName = "response")
    public PreviewDocumentResponse previewDocument(
        @WebParam(name = "PreviewDocument", targetNamespace = "http://pb.com/EngageOne/ws/delivery", partName = "request")
        PreviewDocument request)
        throws DeliveryFault
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.pb.engageone.ws.delivery.DeliverDocumentResponse
     * @throws DeliveryFault
     */
    @WebMethod(action = "http://pb.com/EngageOne/ws/delivery/DeliverDocument")
    @WebResult(name = "DeliverDocumentResponse", targetNamespace = "http://pb.com/EngageOne/ws/delivery", partName = "response")
    public DeliverDocumentResponse deliverDocument(
        @WebParam(name = "DeliverDocument", targetNamespace = "http://pb.com/EngageOne/ws/delivery", partName = "request")
        DeliverDocument request)
        throws DeliveryFault
    ;

}
